<div class="kb-recipe-explorer kb-lightbox">

	<div class="kb-recipe-explorer-close-btn kb-btn-close">Close</div>

	<div class="kb-recipe-explorer-container kb-lightbox-container">
		
		<div class="kb-recipe-explorer-placeholder">
			
			<div class="kb-recipe-explorer-loading">
			
				<p>Loading ... </p>
			
			</div>
			
			<div class="kb-recipe-explorer-timeout">
				
				<p>Sorry :(</p>
				<p>Can't connect ... Please try again later.</p>
				
			</div>
			
		</div>
		
		<iframe id="kb-recipe-explorer-iframe" class="loading" src="" scrolling="no" frameborder="0"></iframe>
		
	</div>

</div>