<div class="kb-wiki-bubble">
	
	<div class="kb-wiki-bubble-entry">
		
		<h2 class="kb-wiki-bubble-title"></h2>
		<img src="" class="kb-wiki-bubble-image" />
		<p class="kb-wiki-bubble-description"></p>
		
	</div>
	
	<div class="kb-wiki-bubble-nutfacts" style="display: none;">
		
		<div class="kb-horizontal-nutrition-container">
			
			<h2><span class="kb-horizontal-nutrition-title"></span> - Nutrition Facts
			<p class="kb-horizontal-nutrition-amount">for 100 grams</p></h2>
			<div class="clear"></div>
			
			<p><strong>Calories</strong> <span class="kb-horizontal-nutrition-calories"></span></p>
			<p>Fat Cal. <span class="kb-horizontal-nutrition-fat-calories"></span></p>
			
			<p class="kb-horizontal-nutrition-table"></p>
							
		</div>
		
	</div>

	<div>
		
		<a href="" title="Nutrition Facts" class="kb-wiki-bubble-btn kb-wiki-bubble-facts-btn">Nutrition Facts</a>
		<a href="" title="Ingredient Description" class="kb-wiki-bubble-btn kb-wiki-bubble-entry-btn" style="display: none;">Description</a>
		<a href="" target="_blank" title="Wikipedia" class="kb-wiki-bubble-btn kb-wiki-bubble-more-btn">Wikipedia</a>

	</div>
	
</div>