
<script>

var kb_ajaxURL = '<?php echo $this->ajaxURL ?>';

</script>

<div id="preloaded-images">
	
	<img src="<?php echo $this->pluginURL ?>/application/assets/img/print-small.png" height="1" width="1">
	<img src="<?php echo $this->pluginURL ?>/application/assets/img/print-small-hover.png" height="1" width="1">
	<img src="<?php echo $this->pluginURL ?>/application/assets/img/dig-in.png" height="1" width="1">
	<img src="<?php echo $this->pluginURL ?>/application/assets/img/dig-in-hover.png" height="1" width="1">
	
</div>

<div class="kb-recipe-container-start"></div>

<div class="kb-recipe-container" recipe-id='<?php echo $this->id; ?>' itemscope itemtype="http://schema.org/Recipe">